name: release

on:
  push:
    tags:
      - '**'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2

      - name: Build
        run: |
          zip -v menu_icons.zip README.md **/*.svg **/*.png
          zip -v menu_icons_PNG.zip README.md **/*.png
          zip -v menu_icons_SVG.zip README.md **/*.svg

      - name: Archive
        uses: actions/upload-artifact@v3
        with:
          name: Bundles
          path: |
            menu_icons.zip
            menu_icons_PNG.zip
            menu_icons_SVG.zip

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: MENU ICONS for Foodservice and Catering (Version ${{ github.ref_name }})
          body: |
            In version ${{ github.ref_name }}, we provide an updated icon set for foodservice and
            catering applications to be used in i.e. apps, web menus or digital signage projects.
            Beside the 14 main and their sub-allergens you'll find some custom declarations like
            "veggie" or "vegan".

            ## File types
            The icons are provided as PNG (in 128x128 pixel) and SVG (to export the icons in the
            resolution you need).

            ## License
            We have made these icons available for you to incorporate into your products under the
            Attribution 4.0 International (CC BY 4.0). Feel free to adapt and share these icons and
            documentation in your products. We'd love attribution in your app's about screen, and
            please not re-sell these icons.
          files: |
            menu_icons.zip
            menu_icons_PNG.zip
            menu_icons_SVG.zip
          draft: true
